name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  bare:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add a repository
        uses: ./
        with:
          uri: https://apt.repos.intel.com/oneapi
          key: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          suite: all
      - name: Install a package
        uses: gerlero/apt-install@v1
        with:
          packages: intel-oneapi-mpi-devel

  container:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ["ubuntu:24.04", "ubuntu:22.04", "ubuntu:20.04", "debian:bullseye", "debian:buster"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add a repository
        uses: ./
        with:
          uri: https://apt.repos.intel.com/oneapi
          key: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          suite: all
      - name: Install a package
        uses: gerlero/apt-install@v1
        with:
          packages: intel-oneapi-mpi-devel
